pub mod atoms;
pub mod archive_skeleton;
pub mod delayed_skeleton;
pub mod home_skeleton;
pub mod post_card_skeleton;
pub mod post_detail_skeleton;
pub mod posts_skeleton;
pub mod search_skeleton;
pub mod tags_skeleton;
