[application]
name = "yggdrasil"
default_platform = "web"
out_dir = "dist"

[web.app]
title = "Yggdrasil - Dioxus SSR"

[web.watcher]
watch_path = ["src", "Cargo.toml"]

[web.resource]
style = ["/style.css"]
script = []

[web.resource.dev]
style = ["/style.css"]
script = []
